//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.1.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class MappingRules {
    
    private MappingRulesMappingRule[] mappingRuleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("MappingRule")]
    public MappingRulesMappingRule[] MappingRule {
        get {
            return this.mappingRuleField;
        }
        set {
            this.mappingRuleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class MappingRulesMappingRule {
    
    private string nameField;
    
    private string featureDataSetField;
    
    private string featureClassField;
    
    private string geometryTypeField;
    
    private string[] matchingExpressionsField;
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string FeatureDataSet {
        get {
            return this.featureDataSetField;
        }
        set {
            this.featureDataSetField = value;
        }
    }
    
    /// <remarks/>
    public string FeatureClass {
        get {
            return this.featureClassField;
        }
        set {
            this.featureClassField = value;
        }
    }
    
    /// <remarks/>
    public string GeometryType {
        get {
            return this.geometryTypeField;
        }
        set {
            this.geometryTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Expression", IsNullable=false)]
    public string[] MatchingExpressions {
        get {
            return this.matchingExpressionsField;
        }
        set {
            this.matchingExpressionsField = value;
        }
    }
}
